baseurl = "http://doodles.mountainmath.ca/"
languageCode = "en-us"
title = "Mountain Doodles"
theme = "hugo-future-imperfect"
preserveTaxonomyNames = true
paginate = 5
disqusShortname = "doodlesmountainmathca"
googleAnalytics = "UA-54516567-1"

[params]
    # Sets the meta tag description, usually reserved for the main page
    description          = "spare time data, analysis, visualization"
    # This will appear on the top left of the navigation bar
    navbarTitle          = "Mountain Doodles"
    # Social media buttons that appear on the sidebar
    socialAppearAtTop    = true
    socialAppearAtBottom = true
    # set this to the section name if section is not post
    viewMorePostLink     = "/blog/"
    #default author, not sure if this works
    author = "Jens von Bergmann"
    dateFormat = "2006/01/02"    
    
# Optional Params
    categoriesByCount    = true
    includeReadingTime   = true
    # The set of favicons used are based on the write-up from this link:
    # https://github.com/audreyr/favicon-cheat-sheet
    # Please see the favicon partial template for more information
    loadFavicon          = true
    faviconVersion       = ""

    # Load custom CSS or JavaScript files. This replaces the deprecated params
    # minifiedFilesCSS and minifiedFilesJS. The variable is an array so that you
    # can load multiple files if necessary. You can also load the standard theme
    # files by adding the value, "default".
    # customCSS            = ["default", "/path/to/file"]
    # customJS             = ["default", "/path/to/file"]

    # Loading min files for exampleSite
    customCSS            = ["/css/main.min.css"] #, "/css/custom.css"
    customJS             = ["/js/main.min.js"]

# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[params.intro]
    header    = "Mountain Doodles"

    paragraph = "Too much data, too little time."

    about     = "Mountain Doodles is an insomnia driven MountainMath side project, born out of random questions, trying to give partial answers through data."

# This will also appear on the sidebar.
# A width of less than 100px is recommended
# This is optional
[params.intro.pic]
    src       = "/img/main/jens_square_small.jpeg"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = false
    imperfect = false
    width     = "150"
    alt       = "Mountain Doodles"

# Adjust the amount of recent posts on the sidebar.
# This is optional. The default value 5 will be used
[params.postAmount]
    sidebar = 5

# Set up your menu items in the navigation bar
# You can use identifier to prepend a font awesome icon to your text
#[[menu.main]]
#    name = "Blog"
#    url = "/blog"
#    identifier = "fa fa-newspaper-o"
#    weight = 1

[[menu.main]]
    name = "Archives"
    url = "/blog/archives"
    weight = 2

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 4

# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar
[social]
    github          = "mountainmath"
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "vb_jens"
    email           = "jens@mountainmath.ca"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/blog/:year/:month/:day/:slug/"
    #posts = "/blog/:year/:month/:day/:slug/"
    #blog = "/blog/:year/:month/:day/:slug/"
